type: original
unet:
  dim: 128
  image_size: 32
  dim_multiply:
  - 1
  - 2
  - 2
  - 2
  attn_resolutions:
  - 16
  dropout: 0.1
  num_res_blocks: 2
ddim:
  0:
    ddim_sampling_steps: 100
    sample_every: 10000
    calculate_fid: true
    num_fid_sample: 6000
    save: true
  1:
    ddim_sampling_steps: 50
    sample_every: 100000
    calculate_fid: true
    num_fid_sample: 60000
    save: true
trainer:
  dataset: cifar10
  batch_size: 128
  lr: 0.0002
  clip: true
  total_step: 600000
  save_and_sample_every: 5000
  fid_estimate_batch_size: 128
  num_samples: 64
